# Generated by Django 3.2.8 on 2022-04-25 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('smartphones', '0005_auto_20211123_1404'),
        ('wearables', '0002_auto_20220425_1341'),
        ('earwear', '0003_auto_20211103_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=254, unique=True)),
                ('article_name_url', models.CharField(max_length=254)),
                ('released_or_not', models.BooleanField(default=False)),
                ('release_date', models.DateField()),
                ('release_time', models.TimeField(blank=True, null=True)),
                ('author', models.CharField(default='Team gadgetin.in', max_length=50)),
                ('type', models.CharField(choices=[('static', 'STATIC'), ('dynamic', 'DYNAMIC')], default='dynamic', max_length=50)),
                ('article_type', models.CharField(blank=True, choices=[('news', 'NEWS'), ('howto', 'HOW TO'), ('reviews', 'REVIEWS'), ('article', 'ARTICLE'), ('weekly news', 'WEEKLY NEWS')], default='news', max_length=50, null=True)),
                ('article_description', models.CharField(blank=True, max_length=500, null=True)),
                ('article_thumbnail', models.ImageField(blank=True, null=True, upload_to='article-thumbnail/')),
                ('content', models.TextField(blank=True, null=True)),
                ('which_earbud', models.ManyToManyField(blank=True, to='earwear.EarModelName')),
                ('which_mobile', models.ManyToManyField(blank=True, to='smartphones.MobileVariant')),
                ('which_wearable', models.ManyToManyField(blank=True, to='wearables.WearModelName')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_images', models.ImageField(blank=True, null=True, upload_to='article-images/')),
                ('articles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.articles')),
            ],
        ),
    ]
