# Generated by Django 3.2.8 on 2022-04-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wearables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wearmodelname',
            name='wear_picture',
            field=models.ImageField(blank=True, null=True, upload_to='wear_picture/'),
        ),
        migrations.AlterField(
            model_name='wearmodelname',
            name='wear_picture_credit',
            field=models.URLField(default='www.gadget4india.com'),
        ),
        migrations.AlterField(
            model_name='wearvariantimage',
            name='wear_image',
            field=models.ImageField(blank=True, null=True, upload_to='wear_image/'),
        ),
    ]
