# Generated by Django 3.2.8 on 2022-08-09 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('mobile_image', models.ImageField(blank=True, null=True, upload_to='model_image/')),
                ('phone_type', models.CharField(choices=[('SMARTPHONE', 'Smartphone'), ('TABLET', 'Tablet'), ('WEARABLE', 'Wearable'), ('EARWEAR', 'Earwear'), ('OTHER', 'Other')], default='Smartphone', max_length=20)),
                ('description', models.CharField(blank=True, max_length=1200, null=True)),
                ('brandName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='release.brandname')),
            ],
        ),
    ]
