# Generated by Django 3.2.8 on 2021-10-22 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EarBrandName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ear_brand_name', models.CharField(max_length=50)),
                ('ear_brand_name_url', models.SlugField()),
            ],
        ),
    ]
