# Generated by Django 3.2.8 on 2021-11-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earwear', '0002_auto_20211102_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earmodelname',
            name='ear_availability',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='earmodelname',
            name='ear_picture',
            field=models.ImageField(blank=True, null=True, upload_to='ear_picture/'),
        ),
    ]
