# Generated by Django 3.2.8 on 2021-11-03 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartphones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilevariant',
            name='price_variant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smartphones.onlineprice'),
        ),
    ]
