# Generated by Django 3.2.8 on 2021-11-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartphones', '0003_auto_20211103_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileperformance',
            name='processor_company',
            field=models.CharField(choices=[('Qualcomm', 'Qualcomm'), ('MediaTek', 'MediaTek'), ('Apple', 'Apple'), ('HiSilicon', 'HiSilicon'), ('Samsung', 'Samsung'), ('Google', 'Google')], max_length=50),
        ),
    ]
