# Generated by Django 3.2.8 on 2022-08-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartphones', '0005_auto_20211123_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilegeneral',
            name='slots',
            field=models.CharField(choices=[('Dual SIM(2) + Dedicated Memory Card Slot', 'Dual SIM(2) + Dedicated Memory Card Slot'), ('Dual SIM(2) (One SIM slot + one hybrid SIM slot)', 'Dual SIM(2) (One SIM slot + one hybrid SIM slot)'), ('One SIM slot + one e-SIM slot', 'One SIM slot + one e-SIM slot'), ('Dual SIM(2)', 'Dual SIM(2)'), ('Single SIM', 'Single SIM'), ('Other', 'Other')], default='Dual SIM(2) + Dedicated Memory Card Slot', max_length=200),
        ),
    ]
